
-- +goose Up
-- SQL in this section is executed when the migration is applied.
create table languages
(
    id SERIAL PRIMARY KEY not null,
    lang_code character(2) not null,
    lang_name character varying(256) not null
);
CREATE index idx_language_lang_code on languages(lang_code);
CREATE unique index idx_language on languages(lang_code, lang_name);

with language_json (doc) as (
   values
    ('
    [
    {"lang_code":"ab", "lang_name":"Abkhaz"},
    {"lang_code":"aa","lang_name":"Afar"},
    {"lang_code":"af","lang_name":"Afrikaans"},
    {"lang_code":"ak","lang_name":"Akan"},
    {"lang_code":"sq","lang_name":"Albanian"},
    {"lang_code":"am","lang_name":"Amharic"},
    {"lang_code":"ar","lang_name":"Arabic"},
    {"lang_code":"an","lang_name":"Aragonese"},
    {"lang_code":"hy","lang_name":"Armenian"},
    {"lang_code":"as","lang_name":"Assamese"},
    {"lang_code":"av","lang_name":"Avaric"},
    {"lang_code":"ae","lang_name":"Avestan"},
    {"lang_code":"ay","lang_name":"Aymara"},
    {"lang_code":"az","lang_name":"Azerbaijani"},
    {"lang_code":"bm","lang_name":"Bambara"},
    {"lang_code":"ba","lang_name":"Bashkir"},
    {"lang_code":"eu","lang_name":"Basque"},
    {"lang_code":"be","lang_name":"Belarusian"},
    {"lang_code":"bn","lang_name":"Bengali"},
    {"lang_code":"bh","lang_name":"Bihari"},
    {"lang_code":"bi","lang_name":"Bislama"},
    {"lang_code":"bs","lang_name":"Bosnian"},
    {"lang_code":"br","lang_name":"Breton"},
    {"lang_code":"bg","lang_name":"Bulgarian"},
    {"lang_code":"my","lang_name":"Burmese"},
    {"lang_code":"ca","lang_name":"Catalan; Valencian"},
    {"lang_code":"ch","lang_name":"Chamorro"},
    {"lang_code":"ce","lang_name":"Chechen"},
    {"lang_code":"ny","lang_name":"Chichewa; Chewa; Nyanja"},
    {"lang_code":"zh","lang_name":"Chinese"},
    {"lang_code":"cv","lang_name":"Chuvash"},
    {"lang_code":"kw","lang_name":"Cornish"},
    {"lang_code":"co","lang_name":"Corsican"},
    {"lang_code":"cr","lang_name":"Cree"},
    {"lang_code":"hr","lang_name":"Croatian"},
    {"lang_code":"cs","lang_name":"Czech"},
    {"lang_code":"da","lang_name":"Danish"},
    {"lang_code":"dv","lang_name":"Divehi; Dhivehi; Maldivian;"},
    {"lang_code":"nl","lang_name":"Dutch"},
    {"lang_code":"en","lang_name":"English"},
    {"lang_code":"eo","lang_name":"Esperanto"},
    {"lang_code":"et","lang_name":"Estonian"},
    {"lang_code":"ee","lang_name":"Ewe"},
    {"lang_code":"fo","lang_name":"Faroese"},
    {"lang_code":"fj","lang_name":"Fijian"},
    {"lang_code":"fi","lang_name":"Finnish"},
    {"lang_code":"fr","lang_name":"French"},
    {"lang_code":"ff","lang_name":"Fula; Fulah; Pulaar; Pular"},
    {"lang_code":"gl","lang_name":"Galician"},
    {"lang_code":"ka","lang_name":"Georgian"},
    {"lang_code":"de","lang_name":"German"},
    {"lang_code":"el","lang_name":"Greek, Modern"},
    {"lang_code":"gn","lang_name":"Guaraní"},
    {"lang_code":"gu","lang_name":"Gujarati"},
    {"lang_code":"ht","lang_name":"Haitian; Haitian Creole"},
    {"lang_code":"ha","lang_name":"Hausa"},
    {"lang_code":"he","lang_name":"Hebrew (modern)"},
    {"lang_code":"hz","lang_name":"Herero"},
    {"lang_code":"hi","lang_name":"Hindi"},
    {"lang_code":"ho","lang_name":"Hiri Motu"},
    {"lang_code":"hu","lang_name":"Hungarian"},
    {"lang_code":"ia","lang_name":"Interlingua"},
    {"lang_code":"id","lang_name":"Indonesian"},
    {"lang_code":"ie","lang_name":"Interlingue"},
    {"lang_code":"ga","lang_name":"Irish"},
    {"lang_code":"ig","lang_name":"Igbo"},
    {"lang_code":"ik","lang_name":"Inupiaq"},
    {"lang_code":"io","lang_name":"Ido"},
    {"lang_code":"is","lang_name":"Icelandic"},
    {"lang_code":"it","lang_name":"Italian"},
    {"lang_code":"iu","lang_name":"Inuktitut"},
    {"lang_code":"ja","lang_name":"Japanese"},
    {"lang_code":"jv","lang_name":"Javanese"},
    {"lang_code":"kl","lang_name":"Kalaallisut, Greenlandic"},
    {"lang_code":"kn","lang_name":"Kannada"},
    {"lang_code":"kr","lang_name":"Kanuri"},
    {"lang_code":"ks","lang_name":"Kashmiri"},
    {"lang_code":"kk","lang_name":"Kazakh"},
    {"lang_code":"km","lang_name":"Khmer"},
    {"lang_code":"ki","lang_name":"Kikuyu, Gikuyu"},
    {"lang_code":"rw","lang_name":"Kinyarwanda"},
    {"lang_code":"ky","lang_name":"Kirghiz, Kyrgyz"},
    {"lang_code":"kv","lang_name":"Komi"},
    {"lang_code":"kg","lang_name":"Kongo"},
    {"lang_code":"ko","lang_name":"Korean"},
    {"lang_code":"ku","lang_name":"Kurdish"},
    {"lang_code":"kj","lang_name":"Kwanyama, Kuanyama"},
    {"lang_code":"la","lang_name":"Latin"},
    {"lang_code":"lb","lang_name":"Luxembourgish, Letzeburgesch"},
    {"lang_code":"lg","lang_name":"Luganda"},
    {"lang_code":"li","lang_name":"Limburgish, Limburgan, Limburger"},
    {"lang_code":"ln","lang_name":"Lingala"},
    {"lang_code":"lo","lang_name":"Lao"},
    {"lang_code":"lt","lang_name":"Lithuanian"},
    {"lang_code":"lu","lang_name":"Luba-Katanga"},
    {"lang_code":"lv","lang_name":"Latvian"},
    {"lang_code":"gv","lang_name":"Manx"},
    {"lang_code":"mk","lang_name":"Macedonian"},
    {"lang_code":"mg","lang_name":"Malagasy"},
    {"lang_code":"ms","lang_name":"Malay"},
    {"lang_code":"ml","lang_name":"Malayalam"},
    {"lang_code":"mt","lang_name":"Maltese"},
    {"lang_code":"mi","lang_name":"Māori"},
    {"lang_code":"mr","lang_name":"Marathi (Marāṭhī)"},
    {"lang_code":"mh","lang_name":"Marshallese"},
    {"lang_code":"mn","lang_name":"Mongolian"},
    {"lang_code":"na","lang_name":"Nauru"},
    {"lang_code":"nv","lang_name":"Navajo, Navaho"},
    {"lang_code":"nb","lang_name":"Norwegian Bokmål"},
    {"lang_code":"nd","lang_name":"North Ndebele"},
    {"lang_code":"ne","lang_name":"Nepali"},
    {"lang_code":"ng","lang_name":"Ndonga"},
    {"lang_code":"nn","lang_name":"Norwegian Nynorsk"},
    {"lang_code":"no","lang_name":"Norwegian"},
    {"lang_code":"ii","lang_name":"Nuosu"},
    {"lang_code":"nr","lang_name":"South Ndebele"},
    {"lang_code":"oc","lang_name":"Occitan"},
    {"lang_code":"oj","lang_name":"Ojibwe, Ojibwa"},
    {"lang_code":"cu","lang_name":"Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic"},
    {"lang_code":"om","lang_name":"Oromo"},
    {"lang_code":"or","lang_name":"Oriya"},
    {"lang_code":"os","lang_name":"Ossetian, Ossetic"},
    {"lang_code":"pa","lang_name":"Panjabi, Punjabi"},
    {"lang_code":"pi","lang_name":"Pāli"},
    {"lang_code":"fa","lang_name":"Persian"},
    {"lang_code":"pl","lang_name":"Polish"},
    {"lang_code":"ps","lang_name":"Pashto, Pushto"},
    {"lang_code":"pt","lang_name":"Portuguese"},
    {"lang_code":"qu","lang_name":"Quechua"},
    {"lang_code":"rm","lang_name":"Romansh"},
    {"lang_code":"rn","lang_name":"Kirundi"},
    {"lang_code":"ro","lang_name":"Romanian, Moldavian, Moldovan"},
    {"lang_code":"ru","lang_name":"Russian"},
    {"lang_code":"sa","lang_name":"Sanskrit (Saṁskṛta)"},
    {"lang_code":"sc","lang_name":"Sardinian"},
    {"lang_code":"sd","lang_name":"Sindhi"},
    {"lang_code":"se","lang_name":"Northern Sami"},
    {"lang_code":"sm","lang_name":"Samoan"},
    {"lang_code":"sg","lang_name":"Sango"},
    {"lang_code":"sr","lang_name":"Serbian"},
    {"lang_code":"gd","lang_name":"Scottish Gaelic; Gaelic"},
    {"lang_code":"sn","lang_name":"Shona"},
    {"lang_code":"si","lang_name":"Sinhala, Sinhalese"},
    {"lang_code":"sk","lang_name":"Slovak"},
    {"lang_code":"sl","lang_name":"Slovene"},
    {"lang_code":"so","lang_name":"Somali"},
    {"lang_code":"st","lang_name":"Southern Sotho"},
    {"lang_code":"es","lang_name":"Spanish; Castilian"},
    {"lang_code":"su","lang_name":"Sundanese"},
    {"lang_code":"sw","lang_name":"Swahili"},
    {"lang_code":"ss","lang_name":"Swati"},
    {"lang_code":"sv","lang_name":"Swedish"},
    {"lang_code":"ta","lang_name":"Tamil"},
    {"lang_code":"te","lang_name":"Telugu"},
    {"lang_code":"tg","lang_name":"Tajik"},
    {"lang_code":"th","lang_name":"Thai"},
    {"lang_code":"ti","lang_name":"Tigrinya"},
    {"lang_code":"bo","lang_name":"Tibetan Standard, Tibetan, Central"},
    {"lang_code":"tk","lang_name":"Turkmen"},
    {"lang_code":"tl","lang_name":"Tagalog"},
    {"lang_code":"tn","lang_name":"Tswana"},
    {"lang_code":"to","lang_name":"Tonga (Tonga Islands)"},
    {"lang_code":"tr","lang_name":"Turkish"},
    {"lang_code":"ts","lang_name":"Tsonga"},
    {"lang_code":"tt","lang_name":"Tatar"},
    {"lang_code":"tw","lang_name":"Twi"},
    {"lang_code":"ty","lang_name":"Tahitian"},
    {"lang_code":"ug","lang_name":"Uighur, Uyghur"},
    {"lang_code":"uk","lang_name":"Ukrainian"},
    {"lang_code":"ur","lang_name":"Urdu"},
    {"lang_code":"uz","lang_name":"Uzbek"},
    {"lang_code":"ve","lang_name":"Venda"},
    {"lang_code":"vi","lang_name":"Vietnamese"},
    {"lang_code":"vo","lang_name":"Volapük"},
    {"lang_code":"wa","lang_name":"Walloon"},
    {"lang_code":"cy","lang_name":"Welsh"},
    {"lang_code":"wo","lang_name":"Wolof"},
    {"lang_code":"fy","lang_name":"Western Frisian"},
    {"lang_code":"xh","lang_name":"Xhosa"},
    {"lang_code":"yi","lang_name":"Yiddish"},
    {"lang_code":"yo","lang_name":"Yoruba"},
    {"lang_code":"za","lang_name":"Zhuang, Chuang"}
]
	 '::json)
)

insert into languages (lang_code, lang_name)
select p.lang_code, p.lang_name
from language_json l
  cross join lateral json_populate_recordset(null::languages, doc) as p;

-- +goose Down
-- SQL in this section is executed when the migration is rolled back.

DROP TABLE IF EXISTS languages;