-- +goose Up
-- SQL in this section is executed when the migration is applied.

DELETE FROM countries;

with country_json (doc) as (
   values 
    ('[
        {"country_name": "Afghanistan", "lang_code": "AF"},
        {"country_name": "Åland Islands", "lang_code": "AX"},
        {"country_name": "Albania", "lang_code": "AL"},
        {"country_name": "Algeria", "lang_code": "DZ"},
        {"country_name": "American Samoa", "lang_code": "AS"},
        {"country_name": "AndorrA", "lang_code": "AD"},
        {"country_name": "Angola", "lang_code": "AO"},
        {"country_name": "Anguilla", "lang_code": "AI"},
        {"country_name": "Antarctica", "lang_code": "AQ"},
        {"country_name": "Antigua and Barbuda", "lang_code": "AG"},
        {"country_name": "Argentina", "lang_code": "AR"},
        {"country_name": "Armenia", "lang_code": "AM"},
        {"country_name": "Aruba", "lang_code": "AW"},
        {"country_name": "Australia", "lang_code": "AU"},
        {"country_name": "Austria", "lang_code": "AT"},
        {"country_name": "Azerbaijan", "lang_code": "AZ"},
        {"country_name": "Bahamas", "lang_code": "BS"},
        {"country_name": "Bahrain", "lang_code": "BH"},
        {"country_name": "Bangladesh", "lang_code": "BD"},
        {"country_name": "Barbados", "lang_code": "BB"},
        {"country_name": "Belarus", "lang_code": "BY"},
        {"country_name": "Belgium", "lang_code": "BE"},
        {"country_name": "Belize", "lang_code": "BZ"},
        {"country_name": "Benin", "lang_code": "BJ"},
        {"country_name": "Bermuda", "lang_code": "BM"},
        {"country_name": "Bhutan", "lang_code": "BT"},
        {"country_name": "Bolivia", "lang_code": "BO"},
        {"country_name": "Bosnia and Herzegovina", "lang_code": "BA"},
        {"country_name": "Botswana", "lang_code": "BW"},
        {"country_name": "Bouvet Island", "lang_code": "BV"},
        {"country_name": "Brazil", "lang_code": "BR"},
        {"country_name": "British Indian Ocean Territory", "lang_code": "IO"},
        {"country_name": "Brunei Darussalam", "lang_code": "BN"},
        {"country_name": "Bulgaria", "lang_code": "BG"},
        {"country_name": "Burkina Faso", "lang_code": "BF"},
        {"country_name": "Burundi", "lang_code": "BI"},
        {"country_name": "Cambodia", "lang_code": "KH"},
        {"country_name": "Cameroon", "lang_code": "CM"},
        {"country_name": "Canada", "lang_code": "CA"},
        {"country_name": "Cape Verde", "lang_code": "CV"},
        {"country_name": "Cayman Islands", "lang_code": "KY"},
        {"country_name": "Central African Republic", "lang_code": "CF"},
        {"country_name": "Chad", "lang_code": "TD"},
        {"country_name": "Chile", "lang_code": "CL"},
        {"country_name": "China", "lang_code": "CN"},
        {"country_name": "Christmas Island", "lang_code": "CX"},
        {"country_name": "Cocos (Keeling) Islands", "lang_code": "CC"},
        {"country_name": "Colombia", "lang_code": "CO"},
        {"country_name": "Comoros", "lang_code": "KM"},
        {"country_name": "Congo", "lang_code": "CG"},
        {"country_name": "Congo, The Democratic Republic of the", "lang_code": "CD"},
        {"country_name": "Cook Islands", "lang_code": "CK"},
        {"country_name": "Costa Rica", "lang_code": "CR"},
        {"country_name": "Cote DIvoire", "lang_code": "CI"},
        {"country_name": "Croatia", "lang_code": "HR"},
        {"country_name": "Cuba", "lang_code": "CU"},
        {"country_name": "Cyprus", "lang_code": "CY"},
        {"country_name": "Czech Republic", "lang_code": "CZ"},
        {"country_name": "Denmark", "lang_code": "DK"},
        {"country_name": "Djibouti", "lang_code": "DJ"},
        {"country_name": "Dominica", "lang_code": "DM"},
        {"country_name": "Dominican Republic", "lang_code": "DO"},
        {"country_name": "Ecuador", "lang_code": "EC"},
        {"country_name": "Egypt", "lang_code": "EG"},
        {"country_name": "El Salvador", "lang_code": "SV"},
        {"country_name": "Equatorial Guinea", "lang_code": "GQ"},
        {"country_name": "Eritrea", "lang_code": "ER"},
        {"country_name": "Estonia", "lang_code": "EE"},
        {"country_name": "Ethiopia", "lang_code": "ET"},
        {"country_name": "Falkland Islands (Malvinas)", "lang_code": "FK"},
        {"country_name": "Faroe Islands", "lang_code": "FO"},
        {"country_name": "Fiji", "lang_code": "FJ"},
        {"country_name": "Finland", "lang_code": "FI"},
        {"country_name": "France", "lang_code": "FR"},
        {"country_name": "French Guiana", "lang_code": "GF"},
        {"country_name": "French Polynesia", "lang_code": "PF"},
        {"country_name": "French Southern Territories", "lang_code": "TF"},
        {"country_name": "Gabon", "lang_code": "GA"},
        {"country_name": "Gambia", "lang_code": "GM"},
        {"country_name": "Georgia", "lang_code": "GE"},
        {"country_name": "Germany", "lang_code": "DE"},
        {"country_name": "Ghana", "lang_code": "GH"},
        {"country_name": "Gibraltar", "lang_code": "GI"},
        {"country_name": "Greece", "lang_code": "GR"},
        {"country_name": "Greenland", "lang_code": "GL"},
        {"country_name": "Grenada", "lang_code": "GD"},
        {"country_name": "Guadeloupe", "lang_code": "GP"},
        {"country_name": "Guam", "lang_code": "GU"},
        {"country_name": "Guatemala", "lang_code": "GT"},
        {"country_name": "Guernsey", "lang_code": "GG"},
        {"country_name": "Guinea", "lang_code": "GN"},
        {"country_name": "Guinea-Bissau", "lang_code": "GW"},
        {"country_name": "Guyana", "lang_code": "GY"},
        {"country_name": "Haiti", "lang_code": "HT"},
        {"country_name": "Heard Island and Mcdonald Islands", "lang_code": "HM"},
        {"country_name": "Holy See (Vatican City State)", "lang_code": "VA"},
        {"country_name": "Honduras", "lang_code": "HN"},
        {"country_name": "Hong Kong", "lang_code": "HK"},
        {"country_name": "Hungary", "lang_code": "HU"},
        {"country_name": "Iceland", "lang_code": "IS"},
        {"country_name": "India", "lang_code": "IN"},
        {"country_name": "Indonesia", "lang_code": "ID"},
        {"country_name": "Iran, Islamic Republic Of", "lang_code": "IR"},
        {"country_name": "Iraq", "lang_code": "IQ"},
        {"country_name": "Ireland", "lang_code": "IE"},
        {"country_name": "Isle of Man", "lang_code": "IM"},
        {"country_name": "Israel", "lang_code": "IL"},
        {"country_name": "Italy", "lang_code": "IT"},
        {"country_name": "Jamaica", "lang_code": "JM"},
        {"country_name": "Japan", "lang_code": "JP"},
        {"country_name": "Jersey", "lang_code": "JE"},
        {"country_name": "Jordan", "lang_code": "JO"},
        {"country_name": "Kazakhstan", "lang_code": "KZ"},
        {"country_name": "Kenya", "lang_code": "KE"},
        {"country_name": "Kiribati", "lang_code": "KI"},
        {"country_name": "Korea, Democratic PeopleS Republic of", "lang_code": "KP"},
        {"country_name": "Korea, Republic of", "lang_code": "KR"},
        {"country_name": "Kuwait", "lang_code": "KW"},
        {"country_name": "Kyrgyzstan", "lang_code": "KG"},
        {"country_name": "Lao PeopleS Democratic Republic", "lang_code": "LA"},
        {"country_name": "Latvia", "lang_code": "LV"},
        {"country_name": "Lebanon", "lang_code": "LB"},
        {"country_name": "Lesotho", "lang_code": "LS"},
        {"country_name": "Liberia", "lang_code": "LR"},
        {"country_name": "Libyan Arab Jamahiriya", "lang_code": "LY"},
        {"country_name": "Liechtenstein", "lang_code": "LI"},
        {"country_name": "Lithuania", "lang_code": "LT"},
        {"country_name": "Luxembourg", "lang_code": "LU"},
        {"country_name": "Macao", "lang_code": "MO"},
        {"country_name": "Macedonia, The Former Yugoslav Republic of", "lang_code": "MK"},
        {"country_name": "Madagascar", "lang_code": "MG"},
        {"country_name": "Malawi", "lang_code": "MW"},
        {"country_name": "Malaysia", "lang_code": "MY"},
        {"country_name": "Maldives", "lang_code": "MV"},
        {"country_name": "Mali", "lang_code": "ML"},
        {"country_name": "Malta", "lang_code": "MT"},
        {"country_name": "Marshall Islands", "lang_code": "MH"},
        {"country_name": "Martinique", "lang_code": "MQ"},
        {"country_name": "Mauritania", "lang_code": "MR"},
        {"country_name": "Mauritius", "lang_code": "MU"},
        {"country_name": "Mayotte", "lang_code": "YT"},
        {"country_name": "Mexico", "lang_code": "MX"},
        {"country_name": "Micronesia, Federated States of", "lang_code": "FM"},
        {"country_name": "Moldova, Republic of", "lang_code": "MD"},
        {"country_name": "Monaco", "lang_code": "MC"},
        {"country_name": "Mongolia", "lang_code": "MN"},
        {"country_name": "Montserrat", "lang_code": "MS"},
        {"country_name": "Morocco", "lang_code": "MA"},
        {"country_name": "Mozambique", "lang_code": "MZ"},
        {"country_name": "Myanmar", "lang_code": "MM"},
        {"country_name": "Namibia", "lang_code": "NA"},
        {"country_name": "Nauru", "lang_code": "NR"},
        {"country_name": "Nepal", "lang_code": "NP"},
        {"country_name": "Netherlands", "lang_code": "NL"},
        {"country_name": "Netherlands Antilles", "lang_code": "AN"},
        {"country_name": "New Caledonia", "lang_code": "NC"},
        {"country_name": "New Zealand", "lang_code": "NZ"},
        {"country_name": "Nicaragua", "lang_code": "NI"},
        {"country_name": "Niger", "lang_code": "NE"},
        {"country_name": "Nigeria", "lang_code": "NG"},
        {"country_name": "Niue", "lang_code": "NU"},
        {"country_name": "Norfolk Island", "lang_code": "NF"},
        {"country_name": "Northern Mariana Islands", "lang_code": "MP"},
        {"country_name": "Norway", "lang_code": "NO"},
        {"country_name": "Oman", "lang_code": "OM"},
        {"country_name": "Pakistan", "lang_code": "PK"},
        {"country_name": "Palau", "lang_code": "PW"},
        {"country_name": "Palestinian Territory, Occupied", "lang_code": "PS"},
        {"country_name": "Panama", "lang_code": "PA"},
        {"country_name": "Papua New Guinea", "lang_code": "PG"},
        {"country_name": "Paraguay", "lang_code": "PY"},
        {"country_name": "Peru", "lang_code": "PE"},
        {"country_name": "Philippines", "lang_code": "PH"},
        {"country_name": "Pitcairn", "lang_code": "PN"},
        {"country_name": "Poland", "lang_code": "PL"},
        {"country_name": "Portugal", "lang_code": "PT"},
        {"country_name": "Puerto Rico", "lang_code": "PR"},
        {"country_name": "Qatar", "lang_code": "QA"},
        {"country_name": "Reunion", "lang_code": "RE"},
        {"country_name": "Romania", "lang_code": "RO"},
        {"country_name": "Russian Federation", "lang_code": "RU"},
        {"country_name": "RWANDA", "lang_code": "RW"},
        {"country_name": "Saint Helena", "lang_code": "SH"},
        {"country_name": "Saint Kitts and Nevis", "lang_code": "KN"},
        {"country_name": "Saint Lucia", "lang_code": "LC"},
        {"country_name": "Saint Pierre and Miquelon", "lang_code": "PM"},
        {"country_name": "Saint Vincent and the Grenadines", "lang_code": "VC"},
        {"country_name": "Samoa", "lang_code": "WS"},
        {"country_name": "San Marino", "lang_code": "SM"},
        {"country_name": "Sao Tome and Principe", "lang_code": "ST"},
        {"country_name": "Saudi Arabia", "lang_code": "SA"},
        {"country_name": "Senegal", "lang_code": "SN"},
        {"country_name": "Serbia and Montenegro", "lang_code": "CS"},
        {"country_name": "Seychelles", "lang_code": "SC"},
        {"country_name": "Sierra Leone", "lang_code": "SL"},
        {"country_name": "Singapore", "lang_code": "SG"},
        {"country_name": "Slovakia", "lang_code": "SK"},
        {"country_name": "Slovenia", "lang_code": "SI"},
        {"country_name": "Solomon Islands", "lang_code": "SB"},
        {"country_name": "Somalia", "lang_code": "SO"},
        {"country_name": "South Africa", "lang_code": "ZA"},
        {"country_name": "South Georgia and the South Sandwich Islands", "lang_code": "GS"},
        {"country_name": "Spain", "lang_code": "ES"},
        {"country_name": "Sri Lanka", "lang_code": "LK"},
        {"country_name": "Sudan", "lang_code": "SD"},
        {"country_name": "Suriname", "lang_code": "SR"},
        {"country_name": "Svalbard and Jan Mayen", "lang_code": "SJ"},
        {"country_name": "Swaziland", "lang_code": "SZ"},
        {"country_name": "Sweden", "lang_code": "SE"},
        {"country_name": "Switzerland", "lang_code": "CH"},
        {"country_name": "Syrian Arab Republic", "lang_code": "SY"},
        {"country_name": "Taiwan, Province of China", "lang_code": "TW"},
        {"country_name": "Tajikistan", "lang_code": "TJ"},
        {"country_name": "Tanzania, United Republic of", "lang_code": "TZ"},
        {"country_name": "Thailand", "lang_code": "TH"},
        {"country_name": "Timor-Leste", "lang_code": "TL"},
        {"country_name": "Togo", "lang_code": "TG"},
        {"country_name": "Tokelau", "lang_code": "TK"},
        {"country_name": "Tonga", "lang_code": "TO"},
        {"country_name": "Trinidad and Tobago", "lang_code": "TT"},
        {"country_name": "Tunisia", "lang_code": "TN"},
        {"country_name": "Turkey", "lang_code": "TR"},
        {"country_name": "Turkmenistan", "lang_code": "TM"},
        {"country_name": "Turks and Caicos Islands", "lang_code": "TC"},
        {"country_name": "Tuvalu", "lang_code": "TV"},
        {"country_name": "Uganda", "lang_code": "UG"},
        {"country_name": "Ukraine", "lang_code": "UA"},
        {"country_name": "United Arab Emirates", "lang_code": "AE"},
        {"country_name": "United Kingdom", "lang_code": "GB"},
        {"country_name": "United States", "lang_code": "US"},
        {"country_name": "United States Minor Outlying Islands", "lang_code": "UM"},
        {"country_name": "Uruguay", "lang_code": "UY"},
        {"country_name": "Uzbekistan", "lang_code": "UZ"},
        {"country_name": "Vanuatu", "lang_code": "VU"},
        {"country_name": "Venezuela", "lang_code": "VE"},
        {"country_name": "Viet Nam", "lang_code": "VN"},
        {"country_name": "Virgin Islands, British", "lang_code": "VG"},
        {"country_name": "Virgin Islands, U.S.", "lang_code": "VI"},
        {"country_name": "Wallis and Futuna", "lang_code": "WF"},
        {"country_name": "Western Sahara", "lang_code": "EH"},
        {"country_name": "Yemen", "lang_code": "YE"},
        {"country_name": "Zambia", "lang_code": "ZM"},
        {"country_name": "Zimbabwe", "lang_code": "ZW"}
        ]'::json)
)
insert into countries (lang_code, country_name)
select p.lang_code, p.country_name
from country_json l
  cross join lateral json_populate_recordset(null::countries, doc) as p;


-- +goose Down
-- SQL in this section is executed when the migration is rolled back.

DELETE FROM countries;