// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pay.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExchangeCurrency struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExchangeCurrencyType string   `protobuf:"bytes,2,opt,name=exchange_currency_type,json=exchangeCurrencyType,proto3" json:"exchange_currency_type,omitempty"`
	AssetCode            string   `protobuf:"bytes,3,opt,name=asset_code,json=assetCode,proto3" json:"asset_code,omitempty"`
	DenomAssetCode       string   `protobuf:"bytes,4,opt,name=denom_asset_code,json=denomAssetCode,proto3" json:"denom_asset_code,omitempty"`
	Decimals             int64    `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
	PaymentNetwork       string   `protobuf:"bytes,6,opt,name=payment_network,json=paymentNetwork,proto3" json:"payment_network,omitempty"`
	EcAssetIssuerPk      string   `protobuf:"bytes,7,opt,name=ec_asset_issuer_pk,json=ecAssetIssuerPk,proto3" json:"ec_asset_issuer_pk,omitempty"`
	DenomPricePerToken   string   `protobuf:"bytes,8,opt,name=denom_price_per_token,json=denomPricePerToken,proto3" json:"denom_price_per_token,omitempty"`
	PricePerToken        string   `protobuf:"bytes,9,opt,name=price_per_token,json=pricePerToken,proto3" json:"price_per_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExchangeCurrency) Reset()         { *m = ExchangeCurrency{} }
func (m *ExchangeCurrency) String() string { return proto.CompactTextString(m) }
func (*ExchangeCurrency) ProtoMessage()    {}
func (*ExchangeCurrency) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{0}
}

func (m *ExchangeCurrency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeCurrency.Unmarshal(m, b)
}
func (m *ExchangeCurrency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeCurrency.Marshal(b, m, deterministic)
}
func (m *ExchangeCurrency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeCurrency.Merge(m, src)
}
func (m *ExchangeCurrency) XXX_Size() int {
	return xxx_messageInfo_ExchangeCurrency.Size(m)
}
func (m *ExchangeCurrency) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeCurrency.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeCurrency proto.InternalMessageInfo

func (m *ExchangeCurrency) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ExchangeCurrency) GetExchangeCurrencyType() string {
	if m != nil {
		return m.ExchangeCurrencyType
	}
	return ""
}

func (m *ExchangeCurrency) GetAssetCode() string {
	if m != nil {
		return m.AssetCode
	}
	return ""
}

func (m *ExchangeCurrency) GetDenomAssetCode() string {
	if m != nil {
		return m.DenomAssetCode
	}
	return ""
}

func (m *ExchangeCurrency) GetDecimals() int64 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *ExchangeCurrency) GetPaymentNetwork() string {
	if m != nil {
		return m.PaymentNetwork
	}
	return ""
}

func (m *ExchangeCurrency) GetEcAssetIssuerPk() string {
	if m != nil {
		return m.EcAssetIssuerPk
	}
	return ""
}

func (m *ExchangeCurrency) GetDenomPricePerToken() string {
	if m != nil {
		return m.DenomPricePerToken
	}
	return ""
}

func (m *ExchangeCurrency) GetPricePerToken() string {
	if m != nil {
		return m.PricePerToken
	}
	return ""
}

type PhaseDataResponse struct {
	Id                       int64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IcoId                    int64               `protobuf:"varint,2,opt,name=ico_id,json=icoId,proto3" json:"ico_id,omitempty"`
	IcoPhaseName             string              `protobuf:"bytes,3,opt,name=ico_phase_name,json=icoPhaseName,proto3" json:"ico_phase_name,omitempty"`
	IcoPhaseStatus           string              `protobuf:"bytes,4,opt,name=ico_phase_status,json=icoPhaseStatus,proto3" json:"ico_phase_status,omitempty"`
	IcoTokenAsset            string              `protobuf:"bytes,5,opt,name=ico_token_asset,json=icoTokenAsset,proto3" json:"ico_token_asset,omitempty"`
	StartTime                int64               `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime                  int64               `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TokensLeft               int64               `protobuf:"varint,8,opt,name=tokens_left,json=tokensLeft,proto3" json:"tokens_left,omitempty"`
	TokenMaxOrderAmount      int64               `protobuf:"varint,9,opt,name=token_max_order_amount,json=tokenMaxOrderAmount,proto3" json:"token_max_order_amount,omitempty"`
	TokenMinOrderAmount      int64               `protobuf:"varint,10,opt,name=token_min_order_amount,json=tokenMinOrderAmount,proto3" json:"token_min_order_amount,omitempty"`
	MaxUserOrders            int64               `protobuf:"varint,11,opt,name=max_user_orders,json=maxUserOrders,proto3" json:"max_user_orders,omitempty"`
	ActiveExchangeCurrencies []*ExchangeCurrency `protobuf:"bytes,12,rep,name=active_exchange_currencies,json=activeExchangeCurrencies,proto3" json:"active_exchange_currencies,omitempty"`
	IcoIssuerPk              string              `protobuf:"bytes,13,opt,name=ico_issuer_pk,json=icoIssuerPk,proto3" json:"ico_issuer_pk,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}            `json:"-"`
	XXX_unrecognized         []byte              `json:"-"`
	XXX_sizecache            int32               `json:"-"`
}

func (m *PhaseDataResponse) Reset()         { *m = PhaseDataResponse{} }
func (m *PhaseDataResponse) String() string { return proto.CompactTextString(m) }
func (*PhaseDataResponse) ProtoMessage()    {}
func (*PhaseDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{1}
}

func (m *PhaseDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhaseDataResponse.Unmarshal(m, b)
}
func (m *PhaseDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhaseDataResponse.Marshal(b, m, deterministic)
}
func (m *PhaseDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhaseDataResponse.Merge(m, src)
}
func (m *PhaseDataResponse) XXX_Size() int {
	return xxx_messageInfo_PhaseDataResponse.Size(m)
}
func (m *PhaseDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PhaseDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PhaseDataResponse proto.InternalMessageInfo

func (m *PhaseDataResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PhaseDataResponse) GetIcoId() int64 {
	if m != nil {
		return m.IcoId
	}
	return 0
}

func (m *PhaseDataResponse) GetIcoPhaseName() string {
	if m != nil {
		return m.IcoPhaseName
	}
	return ""
}

func (m *PhaseDataResponse) GetIcoPhaseStatus() string {
	if m != nil {
		return m.IcoPhaseStatus
	}
	return ""
}

func (m *PhaseDataResponse) GetIcoTokenAsset() string {
	if m != nil {
		return m.IcoTokenAsset
	}
	return ""
}

func (m *PhaseDataResponse) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *PhaseDataResponse) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *PhaseDataResponse) GetTokensLeft() int64 {
	if m != nil {
		return m.TokensLeft
	}
	return 0
}

func (m *PhaseDataResponse) GetTokenMaxOrderAmount() int64 {
	if m != nil {
		return m.TokenMaxOrderAmount
	}
	return 0
}

func (m *PhaseDataResponse) GetTokenMinOrderAmount() int64 {
	if m != nil {
		return m.TokenMinOrderAmount
	}
	return 0
}

func (m *PhaseDataResponse) GetMaxUserOrders() int64 {
	if m != nil {
		return m.MaxUserOrders
	}
	return 0
}

func (m *PhaseDataResponse) GetActiveExchangeCurrencies() []*ExchangeCurrency {
	if m != nil {
		return m.ActiveExchangeCurrencies
	}
	return nil
}

func (m *PhaseDataResponse) GetIcoIssuerPk() string {
	if m != nil {
		return m.IcoIssuerPk
	}
	return ""
}

type CoinPriceRequest struct {
	Base                 *BaseRequest `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	CoinAmount           int64        `protobuf:"varint,2,opt,name=coin_amount,json=coinAmount,proto3" json:"coin_amount,omitempty"`
	ExchangeCurrencyId   int64        `protobuf:"varint,3,opt,name=exchange_currency_id,json=exchangeCurrencyId,proto3" json:"exchange_currency_id,omitempty"`
	IcoPhaseId           int64        `protobuf:"varint,4,opt,name=ico_phase_id,json=icoPhaseId,proto3" json:"ico_phase_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CoinPriceRequest) Reset()         { *m = CoinPriceRequest{} }
func (m *CoinPriceRequest) String() string { return proto.CompactTextString(m) }
func (*CoinPriceRequest) ProtoMessage()    {}
func (*CoinPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{2}
}

func (m *CoinPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinPriceRequest.Unmarshal(m, b)
}
func (m *CoinPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinPriceRequest.Marshal(b, m, deterministic)
}
func (m *CoinPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinPriceRequest.Merge(m, src)
}
func (m *CoinPriceRequest) XXX_Size() int {
	return xxx_messageInfo_CoinPriceRequest.Size(m)
}
func (m *CoinPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CoinPriceRequest proto.InternalMessageInfo

func (m *CoinPriceRequest) GetBase() *BaseRequest {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *CoinPriceRequest) GetCoinAmount() int64 {
	if m != nil {
		return m.CoinAmount
	}
	return 0
}

func (m *CoinPriceRequest) GetExchangeCurrencyId() int64 {
	if m != nil {
		return m.ExchangeCurrencyId
	}
	return 0
}

func (m *CoinPriceRequest) GetIcoPhaseId() int64 {
	if m != nil {
		return m.IcoPhaseId
	}
	return 0
}

type CoinPriceResponse struct {
	ExchangeAmount             string   `protobuf:"bytes,1,opt,name=exchange_amount,json=exchangeAmount,proto3" json:"exchange_amount,omitempty"`
	ExchangeAmountDenomination string   `protobuf:"bytes,2,opt,name=exchange_amount_denomination,json=exchangeAmountDenomination,proto3" json:"exchange_amount_denomination,omitempty"`
	ExchangeAssetCode          string   `protobuf:"bytes,3,opt,name=exchange_asset_code,json=exchangeAssetCode,proto3" json:"exchange_asset_code,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *CoinPriceResponse) Reset()         { *m = CoinPriceResponse{} }
func (m *CoinPriceResponse) String() string { return proto.CompactTextString(m) }
func (*CoinPriceResponse) ProtoMessage()    {}
func (*CoinPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{3}
}

func (m *CoinPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinPriceResponse.Unmarshal(m, b)
}
func (m *CoinPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinPriceResponse.Marshal(b, m, deterministic)
}
func (m *CoinPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinPriceResponse.Merge(m, src)
}
func (m *CoinPriceResponse) XXX_Size() int {
	return xxx_messageInfo_CoinPriceResponse.Size(m)
}
func (m *CoinPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CoinPriceResponse proto.InternalMessageInfo

func (m *CoinPriceResponse) GetExchangeAmount() string {
	if m != nil {
		return m.ExchangeAmount
	}
	return ""
}

func (m *CoinPriceResponse) GetExchangeAmountDenomination() string {
	if m != nil {
		return m.ExchangeAmountDenomination
	}
	return ""
}

func (m *CoinPriceResponse) GetExchangeAssetCode() string {
	if m != nil {
		return m.ExchangeAssetCode
	}
	return ""
}

type CreateOrderRequest struct {
	Base                 *BaseRequest `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UserId               int64        `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IcoPhaseId           int64        `protobuf:"varint,3,opt,name=ico_phase_id,json=icoPhaseId,proto3" json:"ico_phase_id,omitempty"`
	TokenAmount          int64        `protobuf:"varint,4,opt,name=token_amount,json=tokenAmount,proto3" json:"token_amount,omitempty"`
	ExchangeCurrencyId   int64        `protobuf:"varint,5,opt,name=exchange_currency_id,json=exchangeCurrencyId,proto3" json:"exchange_currency_id,omitempty"`
	UserPublicKey        string       `protobuf:"bytes,6,opt,name=user_public_key,json=userPublicKey,proto3" json:"user_public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{4}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetBase() *BaseRequest {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *CreateOrderRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateOrderRequest) GetIcoPhaseId() int64 {
	if m != nil {
		return m.IcoPhaseId
	}
	return 0
}

func (m *CreateOrderRequest) GetTokenAmount() int64 {
	if m != nil {
		return m.TokenAmount
	}
	return 0
}

func (m *CreateOrderRequest) GetExchangeCurrencyId() int64 {
	if m != nil {
		return m.ExchangeCurrencyId
	}
	return 0
}

func (m *CreateOrderRequest) GetUserPublicKey() string {
	if m != nil {
		return m.UserPublicKey
	}
	return ""
}

type CreateOrderResponse struct {
	OrderId                     int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrderStatus                 string   `protobuf:"bytes,2,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	ExchangeValueToPay          string   `protobuf:"bytes,3,opt,name=exchange_value_to_pay,json=exchangeValueToPay,proto3" json:"exchange_value_to_pay,omitempty"`
	ExchangeValueDenominator    string   `protobuf:"bytes,4,opt,name=exchange_value_denominator,json=exchangeValueDenominator,proto3" json:"exchange_value_denominator,omitempty"`
	ExchangeValueDenomAssetCode string   `protobuf:"bytes,5,opt,name=exchange_value_denom_asset_code,json=exchangeValueDenomAssetCode,proto3" json:"exchange_value_denom_asset_code,omitempty"`
	DepositPk                   string   `protobuf:"bytes,6,opt,name=deposit_pk,json=depositPk,proto3" json:"deposit_pk,omitempty"`
	PaymentQrImage              []byte   `protobuf:"bytes,7,opt,name=payment_qr_image,json=paymentQrImage,proto3" json:"payment_qr_image,omitempty"`
	FiatBic                     string   `protobuf:"bytes,8,opt,name=fiat_bic,json=fiatBic,proto3" json:"fiat_bic,omitempty"`
	FiatIban                    string   `protobuf:"bytes,9,opt,name=fiat_iban,json=fiatIban,proto3" json:"fiat_iban,omitempty"`
	FiatRecepientName           string   `protobuf:"bytes,10,opt,name=fiat_recepient_name,json=fiatRecepientName,proto3" json:"fiat_recepient_name,omitempty"`
	FiatPaymentUsage            string   `protobuf:"bytes,11,opt,name=fiat_payment_usage,json=fiatPaymentUsage,proto3" json:"fiat_payment_usage,omitempty"`
	FiatBankName                string   `protobuf:"bytes,12,opt,name=fiat_bank_name,json=fiatBankName,proto3" json:"fiat_bank_name,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{5}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *CreateOrderResponse) GetOrderStatus() string {
	if m != nil {
		return m.OrderStatus
	}
	return ""
}

func (m *CreateOrderResponse) GetExchangeValueToPay() string {
	if m != nil {
		return m.ExchangeValueToPay
	}
	return ""
}

func (m *CreateOrderResponse) GetExchangeValueDenominator() string {
	if m != nil {
		return m.ExchangeValueDenominator
	}
	return ""
}

func (m *CreateOrderResponse) GetExchangeValueDenomAssetCode() string {
	if m != nil {
		return m.ExchangeValueDenomAssetCode
	}
	return ""
}

func (m *CreateOrderResponse) GetDepositPk() string {
	if m != nil {
		return m.DepositPk
	}
	return ""
}

func (m *CreateOrderResponse) GetPaymentQrImage() []byte {
	if m != nil {
		return m.PaymentQrImage
	}
	return nil
}

func (m *CreateOrderResponse) GetFiatBic() string {
	if m != nil {
		return m.FiatBic
	}
	return ""
}

func (m *CreateOrderResponse) GetFiatIban() string {
	if m != nil {
		return m.FiatIban
	}
	return ""
}

func (m *CreateOrderResponse) GetFiatRecepientName() string {
	if m != nil {
		return m.FiatRecepientName
	}
	return ""
}

func (m *CreateOrderResponse) GetFiatPaymentUsage() string {
	if m != nil {
		return m.FiatPaymentUsage
	}
	return ""
}

func (m *CreateOrderResponse) GetFiatBankName() string {
	if m != nil {
		return m.FiatBankName
	}
	return ""
}

type UserOrdersCountRequest struct {
	Base                 *BaseRequest `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UserId               int64        `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PhaseId              int64        `protobuf:"varint,3,opt,name=phase_id,json=phaseId,proto3" json:"phase_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserOrdersCountRequest) Reset()         { *m = UserOrdersCountRequest{} }
func (m *UserOrdersCountRequest) String() string { return proto.CompactTextString(m) }
func (*UserOrdersCountRequest) ProtoMessage()    {}
func (*UserOrdersCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{6}
}

func (m *UserOrdersCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserOrdersCountRequest.Unmarshal(m, b)
}
func (m *UserOrdersCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserOrdersCountRequest.Marshal(b, m, deterministic)
}
func (m *UserOrdersCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserOrdersCountRequest.Merge(m, src)
}
func (m *UserOrdersCountRequest) XXX_Size() int {
	return xxx_messageInfo_UserOrdersCountRequest.Size(m)
}
func (m *UserOrdersCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserOrdersCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserOrdersCountRequest proto.InternalMessageInfo

func (m *UserOrdersCountRequest) GetBase() *BaseRequest {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *UserOrdersCountRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserOrdersCountRequest) GetPhaseId() int64 {
	if m != nil {
		return m.PhaseId
	}
	return 0
}

type UserOrdersRequest struct {
	Base                 *BaseRequest `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UserId               int64        `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderStatus          string       `protobuf:"bytes,3,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	OrderId              int64        `protobuf:"varint,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	IcoPhaseId           int64        `protobuf:"varint,5,opt,name=ico_phase_id,json=icoPhaseId,proto3" json:"ico_phase_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserOrdersRequest) Reset()         { *m = UserOrdersRequest{} }
func (m *UserOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*UserOrdersRequest) ProtoMessage()    {}
func (*UserOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{7}
}

func (m *UserOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserOrdersRequest.Unmarshal(m, b)
}
func (m *UserOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserOrdersRequest.Marshal(b, m, deterministic)
}
func (m *UserOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserOrdersRequest.Merge(m, src)
}
func (m *UserOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_UserOrdersRequest.Size(m)
}
func (m *UserOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserOrdersRequest proto.InternalMessageInfo

func (m *UserOrdersRequest) GetBase() *BaseRequest {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *UserOrdersRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserOrdersRequest) GetOrderStatus() string {
	if m != nil {
		return m.OrderStatus
	}
	return ""
}

func (m *UserOrdersRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *UserOrdersRequest) GetIcoPhaseId() int64 {
	if m != nil {
		return m.IcoPhaseId
	}
	return 0
}

type UserOrder struct {
	Id                                 int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderStatus                        string   `protobuf:"bytes,2,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	IcoPhaseId                         int64    `protobuf:"varint,3,opt,name=ico_phase_id,json=icoPhaseId,proto3" json:"ico_phase_id,omitempty"`
	TokenAmount                        int64    `protobuf:"varint,4,opt,name=token_amount,json=tokenAmount,proto3" json:"token_amount,omitempty"`
	StellarUserPublicKey               string   `protobuf:"bytes,5,opt,name=stellar_user_public_key,json=stellarUserPublicKey,proto3" json:"stellar_user_public_key,omitempty"`
	ExchangeCurrencyId                 int64    `protobuf:"varint,6,opt,name=exchange_currency_id,json=exchangeCurrencyId,proto3" json:"exchange_currency_id,omitempty"`
	ExchangeCurrencyDenominationAmount string   `protobuf:"bytes,7,opt,name=exchange_currency_denomination_amount,json=exchangeCurrencyDenominationAmount,proto3" json:"exchange_currency_denomination_amount,omitempty"`
	PaymentNetwork                     string   `protobuf:"bytes,8,opt,name=payment_network,json=paymentNetwork,proto3" json:"payment_network,omitempty"`
	DepositPk                          string   `protobuf:"bytes,9,opt,name=deposit_pk,json=depositPk,proto3" json:"deposit_pk,omitempty"`
	PaymentTxId                        string   `protobuf:"bytes,10,opt,name=payment_tx_id,json=paymentTxId,proto3" json:"payment_tx_id,omitempty"`
	PaymentRefundTxId                  string   `protobuf:"bytes,11,opt,name=payment_refund_tx_id,json=paymentRefundTxId,proto3" json:"payment_refund_tx_id,omitempty"`
	PaymentQrImage                     []byte   `protobuf:"bytes,12,opt,name=payment_qr_image,json=paymentQrImage,proto3" json:"payment_qr_image,omitempty"`
	ExchangeAmount                     string   `protobuf:"bytes,13,opt,name=exchange_amount,json=exchangeAmount,proto3" json:"exchange_amount,omitempty"`
	ExchangeAssetCode                  string   `protobuf:"bytes,14,opt,name=exchange_asset_code,json=exchangeAssetCode,proto3" json:"exchange_asset_code,omitempty"`
	ExchangeDenomAssetCode             string   `protobuf:"bytes,15,opt,name=exchange_denom_asset_code,json=exchangeDenomAssetCode,proto3" json:"exchange_denom_asset_code,omitempty"`
	FiatBic                            string   `protobuf:"bytes,16,opt,name=fiat_bic,json=fiatBic,proto3" json:"fiat_bic,omitempty"`
	FiatIban                           string   `protobuf:"bytes,17,opt,name=fiat_iban,json=fiatIban,proto3" json:"fiat_iban,omitempty"`
	FiatRecepientName                  string   `protobuf:"bytes,18,opt,name=fiat_recepient_name,json=fiatRecepientName,proto3" json:"fiat_recepient_name,omitempty"`
	FiatPaymentUsage                   string   `protobuf:"bytes,19,opt,name=fiat_payment_usage,json=fiatPaymentUsage,proto3" json:"fiat_payment_usage,omitempty"`
	FiatBankName                       string   `protobuf:"bytes,20,opt,name=fiat_bank_name,json=fiatBankName,proto3" json:"fiat_bank_name,omitempty"`
	ExchangeCurrencyType               string   `protobuf:"bytes,21,opt,name=exchange_currency_type,json=exchangeCurrencyType,proto3" json:"exchange_currency_type,omitempty"`
	AmountReceived                     string   `protobuf:"bytes,22,opt,name=amount_received,json=amountReceived,proto3" json:"amount_received,omitempty"`
	XXX_NoUnkeyedLiteral               struct{} `json:"-"`
	XXX_unrecognized                   []byte   `json:"-"`
	XXX_sizecache                      int32    `json:"-"`
}

func (m *UserOrder) Reset()         { *m = UserOrder{} }
func (m *UserOrder) String() string { return proto.CompactTextString(m) }
func (*UserOrder) ProtoMessage()    {}
func (*UserOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{8}
}

func (m *UserOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserOrder.Unmarshal(m, b)
}
func (m *UserOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserOrder.Marshal(b, m, deterministic)
}
func (m *UserOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserOrder.Merge(m, src)
}
func (m *UserOrder) XXX_Size() int {
	return xxx_messageInfo_UserOrder.Size(m)
}
func (m *UserOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_UserOrder.DiscardUnknown(m)
}

var xxx_messageInfo_UserOrder proto.InternalMessageInfo

func (m *UserOrder) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserOrder) GetOrderStatus() string {
	if m != nil {
		return m.OrderStatus
	}
	return ""
}

func (m *UserOrder) GetIcoPhaseId() int64 {
	if m != nil {
		return m.IcoPhaseId
	}
	return 0
}

func (m *UserOrder) GetTokenAmount() int64 {
	if m != nil {
		return m.TokenAmount
	}
	return 0
}

func (m *UserOrder) GetStellarUserPublicKey() string {
	if m != nil {
		return m.StellarUserPublicKey
	}
	return ""
}

func (m *UserOrder) GetExchangeCurrencyId() int64 {
	if m != nil {
		return m.ExchangeCurrencyId
	}
	return 0
}

func (m *UserOrder) GetExchangeCurrencyDenominationAmount() string {
	if m != nil {
		return m.ExchangeCurrencyDenominationAmount
	}
	return ""
}

func (m *UserOrder) GetPaymentNetwork() string {
	if m != nil {
		return m.PaymentNetwork
	}
	return ""
}

func (m *UserOrder) GetDepositPk() string {
	if m != nil {
		return m.DepositPk
	}
	return ""
}

func (m *UserOrder) GetPaymentTxId() string {
	if m != nil {
		return m.PaymentTxId
	}
	return ""
}

func (m *UserOrder) GetPaymentRefundTxId() string {
	if m != nil {
		return m.PaymentRefundTxId
	}
	return ""
}

func (m *UserOrder) GetPaymentQrImage() []byte {
	if m != nil {
		return m.PaymentQrImage
	}
	return nil
}

func (m *UserOrder) GetExchangeAmount() string {
	if m != nil {
		return m.ExchangeAmount
	}
	return ""
}

func (m *UserOrder) GetExchangeAssetCode() string {
	if m != nil {
		return m.ExchangeAssetCode
	}
	return ""
}

func (m *UserOrder) GetExchangeDenomAssetCode() string {
	if m != nil {
		return m.ExchangeDenomAssetCode
	}
	return ""
}

func (m *UserOrder) GetFiatBic() string {
	if m != nil {
		return m.FiatBic
	}
	return ""
}

func (m *UserOrder) GetFiatIban() string {
	if m != nil {
		return m.FiatIban
	}
	return ""
}

func (m *UserOrder) GetFiatRecepientName() string {
	if m != nil {
		return m.FiatRecepientName
	}
	return ""
}

func (m *UserOrder) GetFiatPaymentUsage() string {
	if m != nil {
		return m.FiatPaymentUsage
	}
	return ""
}

func (m *UserOrder) GetFiatBankName() string {
	if m != nil {
		return m.FiatBankName
	}
	return ""
}

func (m *UserOrder) GetExchangeCurrencyType() string {
	if m != nil {
		return m.ExchangeCurrencyType
	}
	return ""
}

func (m *UserOrder) GetAmountReceived() string {
	if m != nil {
		return m.AmountReceived
	}
	return ""
}

type UserOrdersResponse struct {
	UserOrders           []*UserOrder `protobuf:"bytes,1,rep,name=UserOrders,proto3" json:"UserOrders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserOrdersResponse) Reset()         { *m = UserOrdersResponse{} }
func (m *UserOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*UserOrdersResponse) ProtoMessage()    {}
func (*UserOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{9}
}

func (m *UserOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserOrdersResponse.Unmarshal(m, b)
}
func (m *UserOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserOrdersResponse.Marshal(b, m, deterministic)
}
func (m *UserOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserOrdersResponse.Merge(m, src)
}
func (m *UserOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_UserOrdersResponse.Size(m)
}
func (m *UserOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserOrdersResponse proto.InternalMessageInfo

func (m *UserOrdersResponse) GetUserOrders() []*UserOrder {
	if m != nil {
		return m.UserOrders
	}
	return nil
}

type IcoPhaseResponse struct {
	PhaseName            string   `protobuf:"bytes,1,opt,name=phase_name,json=phaseName,proto3" json:"phase_name,omitempty"`
	StartTime            int64    `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64    `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	CoinAmount           int64    `protobuf:"varint,4,opt,name=coin_amount,json=coinAmount,proto3" json:"coin_amount,omitempty"`
	IsActive             bool     `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IcoPhaseResponse) Reset()         { *m = IcoPhaseResponse{} }
func (m *IcoPhaseResponse) String() string { return proto.CompactTextString(m) }
func (*IcoPhaseResponse) ProtoMessage()    {}
func (*IcoPhaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{10}
}

func (m *IcoPhaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IcoPhaseResponse.Unmarshal(m, b)
}
func (m *IcoPhaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IcoPhaseResponse.Marshal(b, m, deterministic)
}
func (m *IcoPhaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IcoPhaseResponse.Merge(m, src)
}
func (m *IcoPhaseResponse) XXX_Size() int {
	return xxx_messageInfo_IcoPhaseResponse.Size(m)
}
func (m *IcoPhaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IcoPhaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IcoPhaseResponse proto.InternalMessageInfo

func (m *IcoPhaseResponse) GetPhaseName() string {
	if m != nil {
		return m.PhaseName
	}
	return ""
}

func (m *IcoPhaseResponse) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *IcoPhaseResponse) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *IcoPhaseResponse) GetCoinAmount() int64 {
	if m != nil {
		return m.CoinAmount
	}
	return 0
}

func (m *IcoPhaseResponse) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type PayGetTrustStatusRequest struct {
	Base                 *BaseRequest `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UserId               int64        `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId              int64        `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PayGetTrustStatusRequest) Reset()         { *m = PayGetTrustStatusRequest{} }
func (m *PayGetTrustStatusRequest) String() string { return proto.CompactTextString(m) }
func (*PayGetTrustStatusRequest) ProtoMessage()    {}
func (*PayGetTrustStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{11}
}

func (m *PayGetTrustStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayGetTrustStatusRequest.Unmarshal(m, b)
}
func (m *PayGetTrustStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayGetTrustStatusRequest.Marshal(b, m, deterministic)
}
func (m *PayGetTrustStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayGetTrustStatusRequest.Merge(m, src)
}
func (m *PayGetTrustStatusRequest) XXX_Size() int {
	return xxx_messageInfo_PayGetTrustStatusRequest.Size(m)
}
func (m *PayGetTrustStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayGetTrustStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayGetTrustStatusRequest proto.InternalMessageInfo

func (m *PayGetTrustStatusRequest) GetBase() *BaseRequest {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *PayGetTrustStatusRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PayGetTrustStatusRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type PayGetTrustStatusResponse struct {
	HasStrust            bool     `protobuf:"varint,1,opt,name=has_strust,json=hasStrust,proto3" json:"has_strust,omitempty"`
	StellarIssuerAccount string   `protobuf:"bytes,4,opt,name=stellar_issuer_account,json=stellarIssuerAccount,proto3" json:"stellar_issuer_account,omitempty"`
	StellarAssetCode     string   `protobuf:"bytes,5,opt,name=stellar_asset_code,json=stellarAssetCode,proto3" json:"stellar_asset_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayGetTrustStatusResponse) Reset()         { *m = PayGetTrustStatusResponse{} }
func (m *PayGetTrustStatusResponse) String() string { return proto.CompactTextString(m) }
func (*PayGetTrustStatusResponse) ProtoMessage()    {}
func (*PayGetTrustStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{12}
}

func (m *PayGetTrustStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayGetTrustStatusResponse.Unmarshal(m, b)
}
func (m *PayGetTrustStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayGetTrustStatusResponse.Marshal(b, m, deterministic)
}
func (m *PayGetTrustStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayGetTrustStatusResponse.Merge(m, src)
}
func (m *PayGetTrustStatusResponse) XXX_Size() int {
	return xxx_messageInfo_PayGetTrustStatusResponse.Size(m)
}
func (m *PayGetTrustStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PayGetTrustStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PayGetTrustStatusResponse proto.InternalMessageInfo

func (m *PayGetTrustStatusResponse) GetHasStrust() bool {
	if m != nil {
		return m.HasStrust
	}
	return false
}

func (m *PayGetTrustStatusResponse) GetStellarIssuerAccount() string {
	if m != nil {
		return m.StellarIssuerAccount
	}
	return ""
}

func (m *PayGetTrustStatusResponse) GetStellarAssetCode() string {
	if m != nil {
		return m.StellarAssetCode
	}
	return ""
}

type PayGetTransactionRequest struct {
	Base                 *BaseRequest `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UserId               int64        `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId              int64        `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PayGetTransactionRequest) Reset()         { *m = PayGetTransactionRequest{} }
func (m *PayGetTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*PayGetTransactionRequest) ProtoMessage()    {}
func (*PayGetTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{13}
}

func (m *PayGetTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayGetTransactionRequest.Unmarshal(m, b)
}
func (m *PayGetTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayGetTransactionRequest.Marshal(b, m, deterministic)
}
func (m *PayGetTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayGetTransactionRequest.Merge(m, src)
}
func (m *PayGetTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_PayGetTransactionRequest.Size(m)
}
func (m *PayGetTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayGetTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayGetTransactionRequest proto.InternalMessageInfo

func (m *PayGetTransactionRequest) GetBase() *BaseRequest {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *PayGetTransactionRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PayGetTransactionRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type PayGetTransactionResponse struct {
	Transaction          string   `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	ErrorCode            int64    `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayGetTransactionResponse) Reset()         { *m = PayGetTransactionResponse{} }
func (m *PayGetTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*PayGetTransactionResponse) ProtoMessage()    {}
func (*PayGetTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{14}
}

func (m *PayGetTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayGetTransactionResponse.Unmarshal(m, b)
}
func (m *PayGetTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayGetTransactionResponse.Marshal(b, m, deterministic)
}
func (m *PayGetTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayGetTransactionResponse.Merge(m, src)
}
func (m *PayGetTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_PayGetTransactionResponse.Size(m)
}
func (m *PayGetTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PayGetTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PayGetTransactionResponse proto.InternalMessageInfo

func (m *PayGetTransactionResponse) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

func (m *PayGetTransactionResponse) GetErrorCode() int64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type PayExecuteTransactionRequest struct {
	Base                 *BaseRequest `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UserId               int64        `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId              int64        `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Transaction          string       `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PayExecuteTransactionRequest) Reset()         { *m = PayExecuteTransactionRequest{} }
func (m *PayExecuteTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*PayExecuteTransactionRequest) ProtoMessage()    {}
func (*PayExecuteTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{15}
}

func (m *PayExecuteTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayExecuteTransactionRequest.Unmarshal(m, b)
}
func (m *PayExecuteTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayExecuteTransactionRequest.Marshal(b, m, deterministic)
}
func (m *PayExecuteTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayExecuteTransactionRequest.Merge(m, src)
}
func (m *PayExecuteTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_PayExecuteTransactionRequest.Size(m)
}
func (m *PayExecuteTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayExecuteTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayExecuteTransactionRequest proto.InternalMessageInfo

func (m *PayExecuteTransactionRequest) GetBase() *BaseRequest {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *PayExecuteTransactionRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PayExecuteTransactionRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *PayExecuteTransactionRequest) GetTransaction() string {
	if m != nil {
		return m.Transaction
	}
	return ""
}

type TestTransaction struct {
	Base                 *BaseRequest `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	PaymentChannel       string       `protobuf:"bytes,2,opt,name=payment_channel,json=paymentChannel,proto3" json:"payment_channel,omitempty"`
	TxHash               string       `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	RecipientAddress     string       `protobuf:"bytes,4,opt,name=recipient_address,json=recipientAddress,proto3" json:"recipient_address,omitempty"`
	DenomAmount          int64        `protobuf:"varint,5,opt,name=denom_amount,json=denomAmount,proto3" json:"denom_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TestTransaction) Reset()         { *m = TestTransaction{} }
func (m *TestTransaction) String() string { return proto.CompactTextString(m) }
func (*TestTransaction) ProtoMessage()    {}
func (*TestTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{16}
}

func (m *TestTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestTransaction.Unmarshal(m, b)
}
func (m *TestTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestTransaction.Marshal(b, m, deterministic)
}
func (m *TestTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestTransaction.Merge(m, src)
}
func (m *TestTransaction) XXX_Size() int {
	return xxx_messageInfo_TestTransaction.Size(m)
}
func (m *TestTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_TestTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_TestTransaction proto.InternalMessageInfo

func (m *TestTransaction) GetBase() *BaseRequest {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *TestTransaction) GetPaymentChannel() string {
	if m != nil {
		return m.PaymentChannel
	}
	return ""
}

func (m *TestTransaction) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *TestTransaction) GetRecipientAddress() string {
	if m != nil {
		return m.RecipientAddress
	}
	return ""
}

func (m *TestTransaction) GetDenomAmount() int64 {
	if m != nil {
		return m.DenomAmount
	}
	return 0
}

func init() {
	proto.RegisterType((*ExchangeCurrency)(nil), "pb.ExchangeCurrency")
	proto.RegisterType((*PhaseDataResponse)(nil), "pb.PhaseDataResponse")
	proto.RegisterType((*CoinPriceRequest)(nil), "pb.CoinPriceRequest")
	proto.RegisterType((*CoinPriceResponse)(nil), "pb.CoinPriceResponse")
	proto.RegisterType((*CreateOrderRequest)(nil), "pb.CreateOrderRequest")
	proto.RegisterType((*CreateOrderResponse)(nil), "pb.CreateOrderResponse")
	proto.RegisterType((*UserOrdersCountRequest)(nil), "pb.UserOrdersCountRequest")
	proto.RegisterType((*UserOrdersRequest)(nil), "pb.UserOrdersRequest")
	proto.RegisterType((*UserOrder)(nil), "pb.UserOrder")
	proto.RegisterType((*UserOrdersResponse)(nil), "pb.UserOrdersResponse")
	proto.RegisterType((*IcoPhaseResponse)(nil), "pb.IcoPhaseResponse")
	proto.RegisterType((*PayGetTrustStatusRequest)(nil), "pb.PayGetTrustStatusRequest")
	proto.RegisterType((*PayGetTrustStatusResponse)(nil), "pb.PayGetTrustStatusResponse")
	proto.RegisterType((*PayGetTransactionRequest)(nil), "pb.PayGetTransactionRequest")
	proto.RegisterType((*PayGetTransactionResponse)(nil), "pb.PayGetTransactionResponse")
	proto.RegisterType((*PayExecuteTransactionRequest)(nil), "pb.PayExecuteTransactionRequest")
	proto.RegisterType((*TestTransaction)(nil), "pb.TestTransaction")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PayServiceClient is the client API for PayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PayServiceClient interface {
	GetPhaseData(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*PhaseDataResponse, error)
	GetExchangeCurrencyData(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*ExchangeCurrency, error)
	GetUserOrderCount(ctx context.Context, in *UserOrdersCountRequest, opts ...grpc.CallOption) (*IntResponse, error)
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	GetCoinPrice(ctx context.Context, in *CoinPriceRequest, opts ...grpc.CallOption) (*CoinPriceResponse, error)
	GetUserOrders(ctx context.Context, in *UserOrdersRequest, opts ...grpc.CallOption) (*UserOrdersResponse, error)
	FakePaymentTransaction(ctx context.Context, in *TestTransaction, opts ...grpc.CallOption) (*BoolResponse, error)
	PayGetTrustStatus(ctx context.Context, in *PayGetTrustStatusRequest, opts ...grpc.CallOption) (*PayGetTrustStatusResponse, error)
	PayGetTransaction(ctx context.Context, in *PayGetTransactionRequest, opts ...grpc.CallOption) (*PayGetTransactionResponse, error)
	PayExecuteTransaction(ctx context.Context, in *PayExecuteTransactionRequest, opts ...grpc.CallOption) (*Empty, error)
}

type payServiceClient struct {
	cc *grpc.ClientConn
}

func NewPayServiceClient(cc *grpc.ClientConn) PayServiceClient {
	return &payServiceClient{cc}
}

func (c *payServiceClient) GetPhaseData(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*PhaseDataResponse, error) {
	out := new(PhaseDataResponse)
	err := c.cc.Invoke(ctx, "/pb.PayService/GetPhaseData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payServiceClient) GetExchangeCurrencyData(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*ExchangeCurrency, error) {
	out := new(ExchangeCurrency)
	err := c.cc.Invoke(ctx, "/pb.PayService/GetExchangeCurrencyData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payServiceClient) GetUserOrderCount(ctx context.Context, in *UserOrdersCountRequest, opts ...grpc.CallOption) (*IntResponse, error) {
	out := new(IntResponse)
	err := c.cc.Invoke(ctx, "/pb.PayService/GetUserOrderCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/pb.PayService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payServiceClient) GetCoinPrice(ctx context.Context, in *CoinPriceRequest, opts ...grpc.CallOption) (*CoinPriceResponse, error) {
	out := new(CoinPriceResponse)
	err := c.cc.Invoke(ctx, "/pb.PayService/GetCoinPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payServiceClient) GetUserOrders(ctx context.Context, in *UserOrdersRequest, opts ...grpc.CallOption) (*UserOrdersResponse, error) {
	out := new(UserOrdersResponse)
	err := c.cc.Invoke(ctx, "/pb.PayService/GetUserOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payServiceClient) FakePaymentTransaction(ctx context.Context, in *TestTransaction, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/pb.PayService/FakePaymentTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payServiceClient) PayGetTrustStatus(ctx context.Context, in *PayGetTrustStatusRequest, opts ...grpc.CallOption) (*PayGetTrustStatusResponse, error) {
	out := new(PayGetTrustStatusResponse)
	err := c.cc.Invoke(ctx, "/pb.PayService/PayGetTrustStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payServiceClient) PayGetTransaction(ctx context.Context, in *PayGetTransactionRequest, opts ...grpc.CallOption) (*PayGetTransactionResponse, error) {
	out := new(PayGetTransactionResponse)
	err := c.cc.Invoke(ctx, "/pb.PayService/PayGetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payServiceClient) PayExecuteTransaction(ctx context.Context, in *PayExecuteTransactionRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pb.PayService/PayExecuteTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayServiceServer is the server API for PayService service.
type PayServiceServer interface {
	GetPhaseData(context.Context, *IDRequest) (*PhaseDataResponse, error)
	GetExchangeCurrencyData(context.Context, *IDRequest) (*ExchangeCurrency, error)
	GetUserOrderCount(context.Context, *UserOrdersCountRequest) (*IntResponse, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	GetCoinPrice(context.Context, *CoinPriceRequest) (*CoinPriceResponse, error)
	GetUserOrders(context.Context, *UserOrdersRequest) (*UserOrdersResponse, error)
	FakePaymentTransaction(context.Context, *TestTransaction) (*BoolResponse, error)
	PayGetTrustStatus(context.Context, *PayGetTrustStatusRequest) (*PayGetTrustStatusResponse, error)
	PayGetTransaction(context.Context, *PayGetTransactionRequest) (*PayGetTransactionResponse, error)
	PayExecuteTransaction(context.Context, *PayExecuteTransactionRequest) (*Empty, error)
}

func RegisterPayServiceServer(s *grpc.Server, srv PayServiceServer) {
	s.RegisterService(&_PayService_serviceDesc, srv)
}

func _PayService_GetPhaseData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServiceServer).GetPhaseData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PayService/GetPhaseData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServiceServer).GetPhaseData(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayService_GetExchangeCurrencyData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServiceServer).GetExchangeCurrencyData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PayService/GetExchangeCurrencyData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServiceServer).GetExchangeCurrencyData(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayService_GetUserOrderCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOrdersCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServiceServer).GetUserOrderCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PayService/GetUserOrderCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServiceServer).GetUserOrderCount(ctx, req.(*UserOrdersCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PayService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayService_GetCoinPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoinPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServiceServer).GetCoinPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PayService/GetCoinPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServiceServer).GetCoinPrice(ctx, req.(*CoinPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayService_GetUserOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServiceServer).GetUserOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PayService/GetUserOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServiceServer).GetUserOrders(ctx, req.(*UserOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayService_FakePaymentTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServiceServer).FakePaymentTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PayService/FakePaymentTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServiceServer).FakePaymentTransaction(ctx, req.(*TestTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayService_PayGetTrustStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayGetTrustStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServiceServer).PayGetTrustStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PayService/PayGetTrustStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServiceServer).PayGetTrustStatus(ctx, req.(*PayGetTrustStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayService_PayGetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayGetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServiceServer).PayGetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PayService/PayGetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServiceServer).PayGetTransaction(ctx, req.(*PayGetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayService_PayExecuteTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayExecuteTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServiceServer).PayExecuteTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PayService/PayExecuteTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServiceServer).PayExecuteTransaction(ctx, req.(*PayExecuteTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PayService",
	HandlerType: (*PayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPhaseData",
			Handler:    _PayService_GetPhaseData_Handler,
		},
		{
			MethodName: "GetExchangeCurrencyData",
			Handler:    _PayService_GetExchangeCurrencyData_Handler,
		},
		{
			MethodName: "GetUserOrderCount",
			Handler:    _PayService_GetUserOrderCount_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _PayService_CreateOrder_Handler,
		},
		{
			MethodName: "GetCoinPrice",
			Handler:    _PayService_GetCoinPrice_Handler,
		},
		{
			MethodName: "GetUserOrders",
			Handler:    _PayService_GetUserOrders_Handler,
		},
		{
			MethodName: "FakePaymentTransaction",
			Handler:    _PayService_FakePaymentTransaction_Handler,
		},
		{
			MethodName: "PayGetTrustStatus",
			Handler:    _PayService_PayGetTrustStatus_Handler,
		},
		{
			MethodName: "PayGetTransaction",
			Handler:    _PayService_PayGetTransaction_Handler,
		},
		{
			MethodName: "PayExecuteTransaction",
			Handler:    _PayService_PayExecuteTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pay.proto",
}

func init() { proto.RegisterFile("pay.proto", fileDescriptor_0564d675d5c516e0) }

var fileDescriptor_0564d675d5c516e0 = []byte{
	// 1692 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x5f, 0x6f, 0x1b, 0xc7,
	0x11, 0x17, 0x45, 0x49, 0x24, 0x87, 0xa4, 0x48, 0xae, 0xfe, 0x51, 0xb4, 0x05, 0xab, 0xd7, 0xd6,
	0x16, 0xe0, 0x56, 0xad, 0xed, 0xb6, 0x40, 0x81, 0x16, 0xb0, 0x2c, 0xd9, 0x2a, 0xd1, 0xd6, 0xa5,
	0xcf, 0x72, 0x9f, 0x0a, 0x1c, 0x96, 0x77, 0x2b, 0x6b, 0x41, 0xf2, 0xee, 0x7c, 0xbb, 0x54, 0xc9,
	0x4f, 0x91, 0xc7, 0x20, 0x2f, 0x79, 0x0f, 0x10, 0x04, 0xc8, 0x43, 0xde, 0xf3, 0x98, 0x4f, 0x13,
	0x20, 0xdf, 0x20, 0xd8, 0xd9, 0xbd, 0xe3, 0xf1, 0x8e, 0x54, 0x64, 0x40, 0xc9, 0xe3, 0xfd, 0x66,
	0x76, 0x76, 0x76, 0x76, 0xe6, 0x37, 0xb3, 0x07, 0x95, 0x90, 0x4e, 0x8f, 0xc3, 0x28, 0x90, 0x01,
	0x59, 0x0d, 0xfb, 0x9d, 0xda, 0xfb, 0x61, 0xd0, 0xa7, 0x43, 0x8d, 0x58, 0xdf, 0xaf, 0x42, 0xf3,
	0xe5, 0xc4, 0xbd, 0xa2, 0xfe, 0x7b, 0x76, 0x3a, 0x8e, 0x22, 0xe6, 0xbb, 0x53, 0xb2, 0x09, 0xab,
	0xdc, 0x6b, 0x17, 0x0e, 0x0b, 0x47, 0x45, 0x7b, 0x95, 0x7b, 0xe4, 0x4f, 0xb0, 0xcb, 0x8c, 0x8e,
	0xe3, 0x1a, 0x25, 0x47, 0x4e, 0x43, 0xd6, 0x5e, 0x3d, 0x2c, 0x1c, 0x55, 0xec, 0x6d, 0x96, 0xb1,
	0x70, 0x31, 0x0d, 0x19, 0x39, 0x00, 0xa0, 0x42, 0x30, 0xe9, 0xb8, 0x81, 0xc7, 0xda, 0x45, 0xd4,
	0xac, 0x20, 0x72, 0x1a, 0x78, 0x8c, 0x1c, 0x41, 0xd3, 0x63, 0x7e, 0x30, 0x72, 0x52, 0x4a, 0x6b,
	0xa8, 0xb4, 0x89, 0xf8, 0x49, 0xa2, 0xd9, 0x81, 0xb2, 0xc7, 0x5c, 0x3e, 0xa2, 0x43, 0xd1, 0x5e,
	0x47, 0xa7, 0x92, 0x6f, 0xf2, 0x08, 0x1a, 0x21, 0x9d, 0x8e, 0x98, 0x2f, 0x1d, 0x9f, 0xc9, 0xff,
	0x07, 0xd1, 0xa0, 0xbd, 0xa1, 0x8d, 0x18, 0xf8, 0xb5, 0x46, 0xc9, 0x63, 0x20, 0xcc, 0x35, 0x7b,
	0x71, 0x21, 0xc6, 0x2c, 0x72, 0xc2, 0x41, 0xbb, 0x84, 0xba, 0x0d, 0xe6, 0xe2, 0x6e, 0x5d, 0xc4,
	0x7b, 0x03, 0xf2, 0x04, 0x76, 0xb4, 0x6f, 0x61, 0xc4, 0x5d, 0xe6, 0x84, 0x2c, 0x72, 0x64, 0x30,
	0x60, 0x7e, 0xbb, 0x8c, 0xfa, 0x04, 0x85, 0x3d, 0x25, 0xeb, 0xb1, 0xe8, 0x42, 0x49, 0xc8, 0x43,
	0x68, 0x64, 0x95, 0x2b, 0xa8, 0x5c, 0x0f, 0xd3, 0x7a, 0xd6, 0xa7, 0x6b, 0xd0, 0xea, 0x5d, 0x51,
	0xc1, 0xce, 0xa8, 0xa4, 0x36, 0x13, 0x61, 0xe0, 0x0b, 0x96, 0x8b, 0xf8, 0x0e, 0x6c, 0x70, 0x37,
	0x70, 0xb8, 0x87, 0x11, 0x2e, 0xda, 0xeb, 0xdc, 0x0d, 0xba, 0x1e, 0xf9, 0x0d, 0x6c, 0x2a, 0x38,
	0x54, 0xeb, 0x1d, 0x9f, 0x8e, 0xe2, 0xb0, 0xd6, 0xb8, 0x1b, 0xa0, 0xd1, 0xd7, 0x74, 0x84, 0x91,
	0x9d, 0x69, 0x09, 0x49, 0xe5, 0x58, 0xc4, 0x91, 0x8d, 0xf5, 0xde, 0x22, 0xaa, 0x9c, 0x56, 0x9a,
	0xe8, 0xae, 0x8e, 0x0d, 0x06, 0xb8, 0x62, 0xd7, 0xb9, 0x1b, 0xa0, 0xbf, 0x18, 0x17, 0x75, 0x95,
	0x42, 0xd2, 0x48, 0x3a, 0x92, 0x8f, 0x18, 0x06, 0xb8, 0x68, 0x57, 0x10, 0xb9, 0xe0, 0x23, 0x46,
	0xf6, 0xa1, 0xcc, 0x7c, 0x4f, 0x0b, 0x4b, 0x28, 0x2c, 0x31, 0xdf, 0x43, 0xd1, 0x03, 0xa8, 0xa2,
	0x75, 0xe1, 0x0c, 0xd9, 0xa5, 0xc4, 0xf8, 0x15, 0x6d, 0xd0, 0xd0, 0xbf, 0xd8, 0xa5, 0x24, 0xcf,
	0x60, 0x57, 0x6f, 0x3f, 0xa2, 0x13, 0x27, 0x88, 0x3c, 0x16, 0x39, 0x74, 0x14, 0x8c, 0x7d, 0x89,
	0xe1, 0x2b, 0xda, 0x5b, 0x28, 0xfd, 0x37, 0x9d, 0xfc, 0x47, 0xc9, 0x4e, 0x50, 0x94, 0x5a, 0xc4,
	0xfd, 0xf9, 0x45, 0x90, 0x5e, 0xc4, 0xfd, 0xf4, 0xa2, 0x87, 0xd0, 0x50, 0x7b, 0x8c, 0x05, 0x8b,
	0xf4, 0x1a, 0xd1, 0xae, 0xa2, 0x76, 0x7d, 0x44, 0x27, 0xef, 0x04, 0x8b, 0x50, 0x59, 0x10, 0x1b,
	0x3a, 0xd4, 0x95, 0xfc, 0x9a, 0x39, 0xd9, 0xa4, 0xe7, 0x4c, 0xb4, 0x6b, 0x87, 0xc5, 0xa3, 0xea,
	0xd3, 0xed, 0xe3, 0xb0, 0x7f, 0x9c, 0xad, 0x1b, 0xbb, 0xad, 0xd7, 0x65, 0x70, 0xce, 0x04, 0xb1,
	0xa0, 0x8e, 0xf7, 0x99, 0x24, 0x5e, 0x1d, 0xc3, 0x5c, 0x55, 0xd7, 0x6a, 0x92, 0xce, 0xfa, 0xb2,
	0x00, 0xcd, 0xd3, 0x80, 0xfb, 0x98, 0x57, 0x36, 0xfb, 0x30, 0x66, 0x42, 0x92, 0x5f, 0xc3, 0x5a,
	0x9f, 0x0a, 0x86, 0xa9, 0x51, 0x7d, 0xda, 0x50, 0xdb, 0xbe, 0xa0, 0x22, 0x16, 0xdb, 0x28, 0x54,
	0x41, 0x76, 0x03, 0xee, 0xc7, 0x31, 0xd0, 0x29, 0x03, 0x0a, 0x32, 0x47, 0xff, 0x23, 0x6c, 0xe7,
	0x0b, 0x98, 0x7b, 0x98, 0x3d, 0x45, 0x9b, 0x64, 0xcb, 0xb7, 0xeb, 0x91, 0x43, 0xa8, 0xcd, 0x72,
	0x88, 0x7b, 0x98, 0x3f, 0x45, 0x1b, 0xe2, 0xfc, 0xe9, 0x7a, 0xd6, 0x57, 0x05, 0x68, 0xa5, 0xdc,
	0x35, 0x89, 0xfc, 0x08, 0x1a, 0xc9, 0x4e, 0xc6, 0x9d, 0x82, 0x4e, 0xbd, 0x18, 0x36, 0x2e, 0x3d,
	0x87, 0xfb, 0x19, 0x45, 0x07, 0xab, 0x8a, 0xfb, 0x54, 0xf2, 0xc0, 0x37, 0xcc, 0xd2, 0x99, 0x5f,
	0x75, 0x96, 0xd2, 0x20, 0xc7, 0xb0, 0x35, 0xb3, 0x90, 0x25, 0x9a, 0x56, 0xb2, 0x30, 0xa6, 0x11,
	0xeb, 0x87, 0x02, 0x90, 0xd3, 0x88, 0x51, 0xc9, 0xf0, 0xa2, 0x3f, 0x2a, 0xc2, 0x7b, 0x50, 0xc2,
	0xbc, 0x49, 0x0a, 0x72, 0x43, 0x7d, 0x2e, 0x88, 0x53, 0x31, 0x1b, 0x27, 0xf2, 0x2b, 0xa8, 0x99,
	0xfa, 0xd2, 0xe1, 0xd0, 0x91, 0xd4, 0x55, 0xf1, 0x13, 0xd7, 0xb3, 0xbe, 0xf4, 0x7a, 0x1e, 0x42,
	0x03, 0xfd, 0x09, 0xc7, 0xfd, 0x21, 0x77, 0x9d, 0x01, 0x9b, 0x1a, 0xda, 0xab, 0x2b, 0xb8, 0x87,
	0xe8, 0x3f, 0xd9, 0xd4, 0xfa, 0x64, 0x0d, 0xb6, 0xe6, 0xce, 0x6c, 0xae, 0x69, 0x1f, 0xca, 0xba,
	0x6c, 0x12, 0xd6, 0x29, 0xe1, 0xb7, 0xf6, 0x57, 0x8b, 0x0c, 0x73, 0xe8, 0x8b, 0xa8, 0x22, 0x66,
	0x68, 0xe3, 0x09, 0xec, 0x24, 0xfe, 0x5e, 0xd3, 0xe1, 0x98, 0x39, 0x32, 0x70, 0x42, 0x3a, 0x35,
	0xb1, 0x4f, 0x1c, 0xfe, 0xaf, 0x92, 0x5d, 0x04, 0x3d, 0x3a, 0x25, 0x7f, 0x83, 0x4e, 0x66, 0x49,
	0x72, 0xdb, 0x41, 0x64, 0xd8, 0xa9, 0x3d, 0xb7, 0xee, 0x6c, 0x26, 0x27, 0x67, 0xf0, 0x60, 0xd1,
	0xea, 0xf4, 0xb5, 0x6b, 0xde, 0xba, 0x97, 0x37, 0x31, 0xeb, 0x23, 0x07, 0x00, 0x1e, 0x0b, 0x03,
	0xc1, 0xa5, 0xaa, 0x40, 0x1d, 0xaf, 0x8a, 0x41, 0x7a, 0x03, 0x45, 0x9b, 0x71, 0x2b, 0xf9, 0x10,
	0x39, 0x7c, 0x44, 0xdf, 0x6b, 0x36, 0xab, 0x25, 0xbd, 0xe4, 0x4d, 0xd4, 0x55, 0xa8, 0x8a, 0xde,
	0x25, 0xa7, 0xd2, 0xe9, 0x73, 0xd7, 0x74, 0x84, 0x92, 0xfa, 0x7e, 0xc1, 0x5d, 0x72, 0x0f, 0x2a,
	0x28, 0xe2, 0x7d, 0x1a, 0x37, 0x00, 0xd4, 0xed, 0xf6, 0x29, 0x66, 0x2c, 0x0a, 0x23, 0xe6, 0xb2,
	0x90, 0x63, 0xcf, 0x52, 0x1c, 0x0e, 0x3a, 0x63, 0x95, 0xc8, 0x8e, 0x25, 0x48, 0xe4, 0xbf, 0x03,
	0x82, 0xfa, 0xb1, 0x5b, 0x63, 0xa1, 0x7c, 0xaa, 0xa2, 0x7a, 0x53, 0x49, 0x7a, 0x5a, 0xf0, 0x4e,
	0xe1, 0xaa, 0x39, 0x68, 0xaf, 0xa8, 0x3f, 0xd0, 0x86, 0x6b, 0xba, 0x39, 0xa0, 0x6f, 0xd4, 0x1f,
	0x28, 0x9b, 0xd6, 0x07, 0xd8, 0x9d, 0x71, 0xdd, 0xa9, 0x4a, 0xbf, 0xbb, 0x29, 0x84, 0x7d, 0x28,
	0x67, 0x8a, 0xa0, 0x14, 0x1a, 0xa6, 0xf8, 0xba, 0x00, 0xad, 0xd9, 0x9e, 0x77, 0xb3, 0x5d, 0x36,
	0x4b, 0x8b, 0xf9, 0x2c, 0x4d, 0xe7, 0xf8, 0xda, 0x7c, 0x8e, 0x67, 0xab, 0x76, 0x3d, 0xc7, 0x6e,
	0xdf, 0x94, 0xa0, 0x92, 0xf8, 0x9c, 0x6b, 0xcf, 0xb7, 0xa8, 0x91, 0x3b, 0x21, 0x86, 0x3f, 0xc3,
	0x9e, 0x90, 0x6c, 0x38, 0xa4, 0x91, 0x93, 0x2d, 0x77, 0x9d, 0xef, 0xdb, 0x46, 0xfc, 0x2e, 0x5d,
	0xf5, 0x4b, 0xf9, 0x64, 0x63, 0x29, 0x9f, 0xbc, 0x81, 0xdf, 0xe6, 0x57, 0xa4, 0xf9, 0x38, 0x76,
	0x52, 0x0f, 0x4c, 0x56, 0xd6, 0x44, 0x9a, 0x98, 0x8d, 0xef, 0x0b, 0x26, 0xb3, 0xf2, 0xc2, 0xc9,
	0x6c, 0xbe, 0x2c, 0x2b, 0xd9, 0xb2, 0xb4, 0xa0, 0x1e, 0xdb, 0x91, 0x13, 0x75, 0x0a, 0x5d, 0x2e,
	0x55, 0x03, 0x5e, 0x4c, 0xba, 0x1e, 0xf9, 0x03, 0x6c, 0xc7, 0x3a, 0x11, 0xbb, 0x1c, 0xab, 0x59,
	0x04, 0x55, 0x75, 0xa9, 0xb4, 0x8c, 0xcc, 0x46, 0x11, 0x2e, 0x58, 0x54, 0xeb, 0xb5, 0x85, 0xb5,
	0xbe, 0xa0, 0xa1, 0xd5, 0x17, 0x36, 0xb4, 0x25, 0xed, 0x68, 0x73, 0x49, 0x3b, 0x22, 0x7f, 0x85,
	0xfd, 0x44, 0x3f, 0xc7, 0x66, 0x0d, 0x5c, 0x95, 0x4c, 0xdd, 0x19, 0x22, 0x4b, 0xf3, 0x4f, 0xf3,
	0x06, 0xfe, 0x69, 0xdd, 0x8e, 0x7f, 0xc8, 0xc7, 0xf1, 0xcf, 0xd6, 0xad, 0xf9, 0x67, 0x3b, 0xcf,
	0x3f, 0x37, 0xbc, 0x25, 0x76, 0x6e, 0x78, 0x4b, 0x3c, 0x82, 0x86, 0x19, 0x12, 0x94, 0xef, 0xfc,
	0x9a, 0x79, 0xed, 0x5d, 0x7d, 0x0b, 0x1a, 0xb6, 0x0d, 0x6a, 0x9d, 0x02, 0x49, 0x53, 0x8d, 0x69,
	0x77, 0xbf, 0x07, 0x98, 0xa1, 0xed, 0x02, 0x8e, 0x70, 0x75, 0xc5, 0x38, 0x09, 0x6a, 0xa7, 0x14,
	0xac, 0x2f, 0x0a, 0xd0, 0xec, 0x9a, 0x42, 0x4d, 0x6c, 0x1c, 0x00, 0xa4, 0xe6, 0x6e, 0x3d, 0xd4,
	0x54, 0xc2, 0x64, 0xe8, 0x9e, 0x1f, 0x91, 0x57, 0x6f, 0x1a, 0x91, 0x8b, 0xb9, 0x11, 0x39, 0x3d,
	0xbd, 0xad, 0xe5, 0xa6, 0xb7, 0x7b, 0x50, 0xe1, 0xc2, 0xd1, 0xb3, 0x25, 0xd6, 0x7d, 0xd9, 0x2e,
	0x73, 0x71, 0x82, 0xdf, 0x96, 0x80, 0x76, 0x8f, 0x4e, 0xcf, 0x99, 0xbc, 0x88, 0xc6, 0x42, 0x6a,
	0xf2, 0xb9, 0x33, 0x46, 0x4f, 0xf8, 0xb3, 0x38, 0xc7, 0x9f, 0xd6, 0xe7, 0x05, 0xd8, 0x5f, 0xb0,
	0xeb, 0x2c, 0x52, 0x57, 0x54, 0x38, 0x42, 0x2a, 0x19, 0x6e, 0x5e, 0xb6, 0x2b, 0x57, 0x54, 0xbc,
	0x45, 0x40, 0x65, 0x40, 0x4c, 0x6a, 0x66, 0x1e, 0xa6, 0xae, 0x9b, 0x1c, 0x7d, 0xc6, 0x69, 0x7a,
	0x30, 0x3e, 0xd1, 0x32, 0x95, 0x8b, 0xf1, 0xaa, 0x5c, 0xd7, 0x6f, 0x1a, 0xc9, 0x6c, 0xd6, 0x4b,
	0x45, 0x85, 0xfa, 0x42, 0x85, 0x2e, 0xf0, 0x7f, 0xf6, 0xa8, 0xfc, 0x6f, 0x16, 0x94, 0xd4, 0xa6,
	0x26, 0x28, 0x87, 0x50, 0x95, 0x33, 0xd8, 0xe4, 0x4f, 0x1a, 0x52, 0x61, 0x63, 0x51, 0x14, 0x44,
	0xfa, 0x64, 0x26, 0x83, 0x10, 0xc1, 0x23, 0x7d, 0x56, 0x80, 0xfb, 0x3d, 0x3a, 0x7d, 0x39, 0x61,
	0xee, 0x58, 0xb2, 0x5f, 0xf0, 0x5c, 0x59, 0xd7, 0xd7, 0x72, 0xae, 0x5b, 0xdf, 0x15, 0xa0, 0x71,
	0xc1, 0x44, 0xfa, 0xe0, 0xb7, 0x73, 0x27, 0xd5, 0x24, 0x54, 0xd5, 0xfb, 0x6c, 0x68, 0x7a, 0x69,
	0x4c, 0xc3, 0xa7, 0x1a, 0x55, 0x7e, 0xcb, 0x89, 0x73, 0x45, 0xc5, 0x95, 0x69, 0xf5, 0x1b, 0x72,
	0xf2, 0x0f, 0x2a, 0xae, 0xc8, 0x63, 0x68, 0x45, 0xcc, 0xe5, 0x9a, 0xce, 0xa8, 0xe7, 0x45, 0x4c,
	0xc4, 0xaf, 0xdd, 0x66, 0x22, 0x38, 0xd1, 0xb8, 0x6a, 0xb9, 0x86, 0x6a, 0x75, 0xad, 0xe9, 0xbe,
	0x5f, 0xd5, 0xff, 0x1b, 0x10, 0x7a, 0xfa, 0xed, 0x3a, 0x40, 0x8f, 0x4e, 0xdf, 0xb2, 0xe8, 0x9a,
	0xbb, 0x8c, 0xfc, 0x05, 0x6a, 0xe7, 0x4c, 0x26, 0x0f, 0x76, 0x82, 0xac, 0xd1, 0x3d, 0x33, 0xa7,
	0xe8, 0xec, 0xa8, 0xcf, 0xdc, 0x73, 0xde, 0x5a, 0x21, 0xcf, 0x61, 0xef, 0x9c, 0xc9, 0xec, 0x0b,
	0x71, 0x91, 0x89, 0x85, 0x4f, 0x49, 0x6b, 0x85, 0xbc, 0x80, 0xd6, 0x39, 0x93, 0x09, 0x2b, 0xe1,
	0xa8, 0x46, 0x3a, 0x73, 0xa4, 0x35, 0x37, 0xbf, 0x75, 0x30, 0xc4, 0x5d, 0xf5, 0x9d, 0xf2, 0xa2,
	0x9a, 0x9a, 0xfe, 0xc9, 0xae, 0xd2, 0xc8, 0x3f, 0x81, 0x3a, 0x7b, 0x39, 0x3c, 0xb1, 0xf0, 0x77,
	0x3c, 0x7f, 0xf2, 0xce, 0x23, 0xe8, 0x6d, 0xf6, 0x95, 0xaa, 0xc3, 0x90, 0x7b, 0x0c, 0xa2, 0x03,
	0xf5, 0xf4, 0x21, 0x04, 0xd9, 0x99, 0x3f, 0x40, 0x6c, 0x60, 0x37, 0x0b, 0x27, 0x16, 0x4e, 0x60,
	0xf7, 0x15, 0x1d, 0x30, 0xd3, 0x69, 0xd2, 0x09, 0xb6, 0xa5, 0xd6, 0x64, 0xb2, 0xae, 0xd3, 0xc4,
	0x3c, 0x0b, 0x82, 0x61, 0xca, 0x84, 0x0d, 0xad, 0x1c, 0x59, 0x91, 0xfb, 0x78, 0x73, 0x4b, 0x98,
	0xb3, 0x73, 0xb0, 0x44, 0xba, 0xc8, 0xe6, 0xcc, 0xa3, 0x39, 0x9b, 0xd9, 0xfa, 0x9c, 0xb7, 0x99,
	0x23, 0x08, 0x6b, 0x85, 0xbc, 0x82, 0x9d, 0x85, 0x05, 0x4e, 0x0e, 0xcd, 0xca, 0xa5, 0xb5, 0xdf,
	0xa9, 0x60, 0x12, 0x8d, 0x42, 0x39, 0xb5, 0x56, 0xfa, 0x1b, 0xf8, 0x6b, 0xef, 0xd9, 0x8f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xca, 0x04, 0x6a, 0xa4, 0xf9, 0x13, 0x00, 0x00,
}
